# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDAxZDJhOWQ4YzdhOWZjNDNmMTYxY2QxZGVjYTk0ZGM4ZjdlOTc2NTQ2YTdhNzczNjhhNzg2OTk3MjRiMGYyZTBmMmZmODZmODIyMTRjNGJlMjk2NGYxYjE5ZDc5NmUxZTFjM2MwNTZkYWQzNzQzZDhkZjg2MGQ5MDFiNGM5OGM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
